"""empty message

Revision ID: 13e6e589273b
Revises: 441e678a71ec
Create Date: 2018-07-03 22:00:53.064717

"""

# revision identifiers, used by Alembic.
revision = '13e6e589273b'
down_revision = '441e678a71ec'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reshwap_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('profile_pic', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('signup_date', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reshwap_users')
    # ### end Alembic commands ###
