"""empty message

Revision ID: 6b0ff1b0d00f
Revises: 13e6e589273b
Create Date: 2018-07-03 22:10:16.505427

"""

# revision identifiers, used by Alembic.
revision = '6b0ff1b0d00f'
down_revision = '13e6e589273b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reshwap_users', sa.Column('last_login', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reshwap_users', 'last_login')
    # ### end Alembic commands ###
