"""empty message

Revision ID: ab15de36b1c1
Revises: None
Create Date: 2019-07-04 00:18:37.068103

"""

# revision identifiers, used by Alembic.
revision = 'ab15de36b1c1'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reshwap_items', sa.Column('school', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reshwap_items', 'school')
    # ### end Alembic commands ###
