"""empty message

Revision ID: b1a862572c83
Revises: 6b0ff1b0d00f
Create Date: 2018-08-21 21:52:11.500024

"""

# revision identifiers, used by Alembic.
revision = 'b1a862572c83'
down_revision = '6b0ff1b0d00f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reshwap_users', sa.Column('g_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reshwap_users', 'g_token')
    # ### end Alembic commands ###
