"""empty message

Revision ID: 1b94554d8b21
Revises: None
Create Date: 2018-07-03 10:21:14.797124

"""

# revision identifiers, used by Alembic.
revision = '1b94554d8b21'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reshwap_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uploader', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('details', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('money', sa.String(), nullable=True),
    sa.Column('exchange', sa.String(), nullable=True),
    sa.Column('image_one', sa.String(), nullable=True),
    sa.Column('image_two', sa.String(), nullable=True),
    sa.Column('image_three', sa.String(), nullable=True),
    sa.Column('image_four', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('isCompleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reshwap_items')
    # ### end Alembic commands ###
